name: ${project.name}
main: net.novucs.ftop.FactionsTopPlugin
version: ${project.version}
description: ${project.description}
author: novucs
depend: [Factions]
commands:
  ftop:
    aliases: [factionstop]
    description: Displays factions in order of worth.
    permission: "factionstop.use"
    permission-message: "§cYou do not have permission."
    usage: /<command> [page]
permissions:
  factionstop.use: {default: true}