name: ${project.name}
main: net.novucs.ftop.FactionsTopPlugin
version: '${minecraft.plugin.version}'
description: ${project.description}
author: novucs
softdepend: [EpicSpawners, Essentials, Factions, LegacyFactions, Vault, MVdWPlaceholderAPI, PlaceholderAPI]

commands:
  ftop:
    aliases: [factionstop]
    description: Displays factions in order of worth.
    usage: /<command> [page]

  ftopgui:
    aliases: [factionstopgui]
    description: Displays top factions with a GUI.
    usage: /<command> [page]

  ftoprecalculate:
    aliases: [factionstoprecalculate, ftoprecalc, ftoprec]
    description: Recalculates all existing claims.
    usage: /<command>

  ftopreload:
    aliases: [factionstopreload, ftopr]
    description: Reloads the plugin configuration.
    usage: /<command>

  ftopversion:
    aliases: [factionstopversion, ftopv]
    description: Sends the version message.
    usage: /<command>

permissions:
  factionstop.user:
    default: true
    children:
      factionstop.use: true

  factionstop.admin:
    default: op
    children:
      factionstop.recalculate: true
      factionstop.reload: true
      factionstop.sign.break: true
      factionstop.sign.create: true
      factionstop.user: true

  factionstop.*:
    default: false
    children:
      factionstop.admin: true

  factionstop.use: {default: false}
  factionstop.recalculate: {default: false}
  factionstop.reload: {default: false}
  factionstop.sign.break: {default: false}
  factionstop.sign.create: {default: false}